### ISSUE TITLE
No credit?

### ISSUE THREAD

**Issue by vixrant** [arghyadeep99/Word-Suggester#1]
Ah well it was MIT licensed anyway.

**Comment by vixrant** [comment]
Oh btw you aren't allowed to change the licensee name in MIT license. That allows me for a DCMA takedown.

https://opensource.stackexchange.com/questions/5120/what-if-somebody-removed-my-name-from-mit-license

**Comment by arghyadeep99** [comment]
Code credits given in README. Let me know if any more issues. Sorry for the delay. I checked this repo only today. I apologize for the inconvenience and no mention of credits to date.
